# Pull the base image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=pqgotest
ENV POSTGRES_DB=pqgotest
ENV POSTGRES_PASSWORD=password

# Default command to run on container start
CMD ["postgres"]
